services:
  trade-imports-defra-id-stub:
    profiles: [stubs]
    environment:
      - PORT=3007
      - AUTH_PASSWORD=${AUTH_PASSWORD:-Password123}
      - SECURE_COOKIE=false
      - WELL_KNOWN_HOST_OVERRIDE=http://localhost:3007
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 3s
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:3007/health
      timeout: 5s
    image: defradigital/trade-imports-defra-id-stub:${TRADE_IMPORTS_DEFRA_ID_STUB:-latest}
    ports:
      - '3007:3007'
  trade-imports-stub:
    profiles: [stubs]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./shared.env
    environment:
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=50.0 -XX:TieredStopAtLevel=1
      - PORT=8087
      - SPRING_PROFILES_ACTIVE=local
      - MONGO_DATABASE=trade-imports-stub
      - AWS_EMF_AGENT_ENDPOINT=http://host.docker.internal:4566
      - LOG_LEVEL=INFO
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 30s
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8087/health
      timeout: 5s
    image: defradigital/trade-imports-stub:${TRADE_IMPORTS_STUB:-latest}
    mem_limit: 1g
    ports:
      - '8087:8087'
